export const DEFAULT_TEXTS: Record<string, string> = {
  // Navbar
  'nav_logo_title': 'DENTAL MASTER',
  'nav_logo_sub': 'Academy',
  'nav_link_1': 'Académies',
  'nav_link_2': 'Produit',
  'nav_link_3': 'Application',
  'nav_link_4': 'Tarifs',
  'nav_link_5': 'FAQ',
  'nav_cta': 'WhatsApp',
  'nav_admin': 'Admin',

  // Hero
  'hero_badge': 'Bibliothèque Clinique Premium — Francophones',
  'hero_title_1': 'DENTAL',
  'hero_title_2': 'MASTER',
  'hero_title_3': 'ACADEMY',
  'hero_subtitle': 'La première bibliothèque clinique hors ligne destinée aux chirurgiens-dentistes francophones.',
  'hero_stat_1_label': 'Cas Cliniques Réels',
  'hero_stat_2_label': 'Académies Expertes',
  'hero_stat_3_label': 'Heures de Vidéo HD',
  'hero_stat_4_label': 'Accès à Vie & Hors Ligne',
  'hero_cta_1': 'Commander via WhatsApp',
  'hero_cta_2': 'Découvrir les Académies',

  // ProductShowcase
  'showcase_label': 'Le Produit Physique',
  'showcase_title_1': 'Une Bibliothèque',
  'showcase_title_2': 'Tangible.',
  'showcase_desc': "Pas de cours en ligne. Pas d'abonnement. Recevez un disque dur SSD physique contenant l'application complète, ou faites-la installer directement sur votre poste. Une expérience premium, pensée pour la pratique clinique.",
  'showcase_pill_1': 'SSD Haute Vitesse',
  'showcase_pill_2': 'Hors Ligne',
  'showcase_pill_3': 'Installation Pro',
  'showcase_pill_4': 'Aucune Connexion Requise',
  'showcase_badge_title': 'Mode Hors Ligne',
  'showcase_badge_desc': "Accédez à tout, sans internet.",
  'showcase_floating_badge': 'Hors Ligne',

  // AppPreview
  'app_label': "L'Expérience Utilisateur",
  'app_title_1': 'Une Interface',
  'app_title_2': 'Médicale',
  'app_desc': 'Un logiciel pensé pour les cliniciens. Recherche instantanée, catégories claires, lecteur vidéo haute définition.',
  'app_shot1_badge': 'Dashboard',
  'app_shot1_title': "Vue d'ensemble clinique",
  'app_shot1_desc': "Accédez à tous vos cas en un coup d'œil.",
  'app_shot2_badge': 'Lecteur HD',
  'app_shot2_title': 'Lecture haute définition',
  'app_shot2_desc': 'Vidéos HD organisées et instantanément accessibles.',
  'app_feat_1': 'Recherche Instantanée',
  'app_feat_2': 'Catégories Claires',
  'app_feat_3': 'Lecteur HD Intégré',
  'app_feat_4': 'Organisation Pro',

  // Academies
  'academies_label': 'Les Académies',
  'academies_title_1': '8 Académies',
  'academies_title_2': 'Expertes',
  'academies_desc': 'Chaque académie regroupe des cas cliniques réels, filmés en haute définition et organisés par spécialité.',
  'academy_1_title': 'Implantologie Chirurgicale',
  'academy_1_desc': "Techniques avancées d'implantologie, greffes osseuses et sinus lifts.",
  'academy_2_title': 'Dentisterie Esthétique & Facettes',
  'academy_2_desc': 'Facettes céramiques, smile design et transformations esthétiques complètes.',
  'academy_3_title': 'Dentisterie Restauratrice Adhésive',
  'academy_3_desc': 'Techniques adhésives modernes, composites et restauration directe.',
  'academy_4_title': 'Endodontie Avancée',
  'academy_4_desc': 'Traitement canalaire complexe, microscope et retraitements endodontiques.',
  'academy_5_title': 'Parodontologie & Chirurgie Muco-Gingivale',
  'academy_5_desc': 'Chirurgie parodontale, greffes gingivales et régénération tissulaire.',
  'academy_6_title': 'Orthodontie Moderne',
  'academy_6_desc': 'Alignateurs, techniques numériques et gestion des malocclusions.',
  'academy_7_title': 'Prothèse Dentaire',
  'academy_7_desc': 'Prothèses fixes et amovibles, CAD/CAM et solutions prothétiques numériques.',
  'academy_8_title': 'Pédodontie & Prévention',
  'academy_8_desc': 'Soins pédiatriques, prévention et gestion du patient enfant.',
  'academy_9_title': 'SAHOS & Orthèses',
  'academy_9_desc': "Syndrome d'apnées, orthèses d'avancée mandibulaire et médecine du sommeil.",
  'academy_10_title': 'Ergonomie & Gestion du Praticien',
  'academy_10_desc': 'Optimisation du cabinet, ergonomie posturale et gestion de pratique.',

  // Benefits
  'benefits_label': 'Ce Que Vous Recevez',
  'benefits_title_1': '8 Raisons',
  'benefits_title_2': 'Incontournables',
  'benefits_desc': "Un investissement unique pour une ressource clinique d'une valeur durable.",
  'benefit_1_title': '146 Cas Cliniques',
  'benefit_1_desc': 'Une bibliothèque complète de cas réels, filmés en clinique.',
  'benefit_2_title': '8 Académies',
  'benefit_2_desc': 'Toutes les spécialités dentaires réunies en un seul produit.',
  'benefit_3_title': 'Accès à Vie',
  'benefit_3_desc': 'Payez une fois. Accédez pour toujours, sans limitation.',
  'benefit_4_title': 'Fonctionne Hors Ligne',
  'benefit_4_desc': "Aucune connexion internet requise. Tout est stocké localement.",
  'benefit_5_title': 'Aucun Abonnement',
  'benefit_5_desc': 'Pas de frais récurrents. Un paiement unique, définitif.',
  'benefit_6_title': 'Organisation Professionnelle',
  'benefit_6_desc': 'Cas classés par spécialité, difficulté et procédure.',
  'benefit_7_title': 'Vidéos HD',
  'benefit_7_desc': 'Qualité haute définition pour observer chaque détail clinique.',
  'benefit_8_title': 'Interface Logicielle Premium',
  'benefit_8_desc': 'Une application moderne, élégante et intuitive.',

  // Comparison
  'comparison_label': 'Comparaison',
  'comparison_title_1': 'DMA vs',
  'comparison_title_2': 'Cours en Ligne',
  'comparison_col_1': 'Critère',
  'comparison_col_2': 'Dental Master',
  'comparison_col_3': 'Cours en Ligne',
  'comp_feat_1': 'Accès hors ligne',
  'comp_feat_2': 'Accès à vie',
  'comp_feat_3': 'Aucun abonnement',
  'comp_feat_4': 'Logiciel premium',
  'comp_feat_5': 'Disque dur externe SSD',
  'comp_feat_6': 'Vidéos HD organisées',
  'comp_feat_7': 'Cas cliniques réels',
  'comp_feat_8': 'Mises à jour gratuites',
  'comp_feat_9': 'Aucune connexion requise',
  'comp_feat_10': 'Installation personnalisée',

  // Pricing
  'pricing_label': 'Tarification',
  'pricing_title_1': 'Un Paiement.',
  'pricing_title_2': 'Pour Toujours.',
  'pricing_desc': 'Choisissez l\'option qui vous convient. Aucun abonnement, aucun frais caché.',
  'plan_ssd_name': 'Disque Dur Externe SSD',
  'plan_ssd_badge': 'Le Plus Populaire',
  'plan_ssd_feat_1': 'Application complète',
  'plan_ssd_feat_2': 'Disque dur externe SSD',
  'plan_ssd_feat_3': '146 Cas Cliniques',
  'plan_ssd_feat_4': 'Accès à vie',
  'plan_ssd_feat_5': 'Fonctionne hors ligne',
  'plan_ssd_feat_6': 'Support premium',
  'plan_install_name': 'Installation sur Votre Poste',
  'plan_install_badge': 'Économique',
  'plan_install_feat_1': 'Copie complète',
  'plan_install_feat_2': 'Organisation professionnelle',
  'plan_install_feat_3': 'Installation personnalisée',
  'plan_install_feat_4': 'Accès à vie',
  'plan_install_feat_5': 'Fonctionne hors ligne',
  'pricing_cta': 'Commander via WhatsApp',

  // FAQ
  'faq_label': 'Questions Fréquentes',
  'faq_title_1': 'Vos',
  'faq_title_2': 'Questions',
  'faq_1_q': "Qu'est-ce que Dental Master Academy exactement ?",
  'faq_1_a': "Dental Master Academy est une bibliothèque clinique hors ligne premium contenant 146 cas cliniques réels en vidéo HD, répartis sur 8 académies. Elle est livrée sur disque dur SSD physique ou installée directement sur votre ordinateur.",
  'faq_2_q': "Ai-je besoin d'une connexion internet ?",
  'faq_2_a': "Non. Une fois installée ou reçue sur le SSD, l'application fonctionne entièrement hors ligne. Aucune connexion internet n'est requise pour accéder aux contenus.",
  'faq_3_q': "Y a-t-il un abonnement ou des frais récurrents ?",
  'faq_3_a': "Aucunement. Vous payez un seul paiement unique et bénéficiez d'un accès à vie à l'ensemble du contenu. Aucun abonnement, aucun frais caché.",
  'faq_4_q': "Quelle est la différence entre les deux options ?",
  'faq_4_a': "L'option SSD (19 900 DA) inclut un disque dur externe physique livré chez vous. L'option installation (14 900 DA) consiste en une installation personnalisée directement sur votre poste informatique.",
  'faq_5_q': "Les vidéos sont-elles en haute définition ?",
  'faq_5_a': "Oui, toutes les vidéos sont en HD et filmées en conditions cliniques réelles, permettant d'observer chaque détail des procédures.",
  'faq_6_q': "Comment puis-je commander ?",
  'faq_6_a': "Cliquez sur le bouton WhatsApp pour nous contacter directement au +213 670 491 102. Notre équipe vous guidera dans le processus de commande et de livraison.",
  'faq_7_q': "Le contenu est-il disponible en français ?",
  'faq_7_a': "Oui, Dental Master Academy est destiné aux chirurgiens-dentistes francophones. L'ensemble du contenu est en français.",

  // FinalCTA
  'final_cta_label': "L'Investissement Durable",
  'final_cta_desc': "Rejoignez les chirurgiens-dentistes francophones qui ont choisi l'accès à vie à une formation clinique premium, hors ligne.",
  'final_cta_button': 'Commander via WhatsApp',
  'final_cta_phone': '+213 670 491 102',
  'final_trust_1': 'Paiement Unique',
  'final_trust_2': 'Accès à Vie',
  'final_trust_3': 'Hors Ligne',
  'final_trust_4': 'Aucun Abonnement',
  'footer_address': 'Adgency Academy, 146 Carriel, Danforth.',
  'footer_copyright': '© 2026 Dental Master Academy. Tous droits réservés.',

  // PurchaseForm
  'form_label': 'Commander Maintenant',
  'form_title_1': 'Remplissez le',
  'form_title_2': 'Formulaire',
  'form_desc': 'Recevez votre bibliothèque clinique en quelques jours.',
  'form_success_title': 'Demande envoyée !',
  'form_success_desc': "Nous avons bien reçu votre demande. Notre équipe vous contactera très prochainement pour finaliser votre commande.",
  'form_success_btn': 'Nouvelle demande',
  'form_btn': 'Envoyer ma commande',
  'form_note': 'En soumettant ce formulaire, vous serez contacté pour finaliser votre commande.',

  // StickyWhatsApp
  'sticky_top': 'Commander via',
  'sticky_bottom': 'WhatsApp',
};
